server:
  port: 8080
spring:
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: ${RABBITMQ_USER}
#    password: ${RABBITMQ_PASSWORD}
  graphql:
    graphiql:
      enabled: true
  r2dbc:
    driver: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    pool:
      enabled: false
      initial-size: 5
