server:
  port: 8081
spring:
  ai:
    azure:
      openai:
        endpoint: ${AZURE_ENDPOINT}
        api-key: ${AZURE_API_KEY}
        chat:
          options:
            deployment_name: ${AZURE_DEPLOYMENT}
  graphql:
    graphiql:
      enabled: true
  r2dbc:
    driver: h2
    # The connection URL is set to r2dbc:h2:file:///./[database-name], which indicates that you are using H2 disk-based database.
    # url: r2dbc:h2:file:///./finance?options=DB_CLOSE_DELAY=-1
    url: r2dbc:h2:mem:///finance?options=DB_CLOSE_DELAY=-1
    pool:
      enabled: true
      initial-size: 5
app:
  version-code-name: ${APP_VERSION_CODE_NAME}