---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "springwebfluxdb"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-webflux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-webflux
  template:
    metadata:
      labels:
        app: spring-webflux
    spec:
      containers:
        - name: spring-webflux
          image: yourdockerhubusername/spring-webflux-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-webflux-service
spec:
  selector:
    app: spring-webflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>


